version: '3.9'

services:
  web:
    build: 
      dockerfile: ./docker/php-apache/Dockerfile

    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  mongo:
    image: mongo
    ports:
      - 27017:27017